baseURL = 'https://niklaushirt.github.io/cp4waiops-training/'
languageCode = 'en-us'
title = 'IBM CloudPak for Watson AIOps - Training'
#theme = "learn"
theme = "hugo-geekdoc"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
pygmentsStyle = "monokai"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

canonifyURLs = true

